spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          skipSslValidation: 'true'
          clone-on-start: 'true'
          uri: https://github.com/madeeasycodinglife/spring-boot-config-server-location.git
          default-label: main # The branch name or commit hash in your GitHub repository
          search-paths:
            - configuration/configuration #  The directory that contains the configuration files here configuration(1)/configuration(2) i.e. first configuration file(1) indicating
#            first folder and second configuration(2)  indicating second folder from where configuration files are to be loaded

management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: '8888'

# Spring Cloud Config Server exposes the following REST endpoints
# to get application specific configuration properties:
#  /{application}/{profile}[/{label}]
#  /{application}-{profile}.yml
#  /{label}/{application}-{profile}.yml
#  /{application}-{profile}.properties
#  /{label}/{application}-{profile}.properties